### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by ynoval** [RyanMullins/angular-hammer#75]
I try to add it to my project but this error appear:

error Invalid Version: 2.2-jsdw

$>  bower install --save ryanmullins-angular-hammer

bower ryanmullins-angular-hammer#\*       not-cached https://github.com/ryanmullins/angular-hammer.git#*
bower ryanmullins-angular-hammer#\*          resolve https://github.com/ryanmullins/angular-hammer.git#*
bower ryanmullins-angular-hammer#\*         checkout v2.2.0
bower ryanmullins-angular-hammer#\*     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower ryanmullins-angular-hammer#\*            error Invalid Version: 2.2-jsdw

Stack trace:
TypeError: Invalid Version: 2.2-jsdw
    at new SemVer (/usr/local/lib/node_modules/bower/lib/node_modules/semver/semver.js:273:11)
    at compare (/usr/local/lib/node_modules/bower/lib/node_modules/semver/semver.js:460:10)
    at Object.neq (/usr/local/lib/node_modules/bower/lib/node_modules/semver/semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:209:56)
    at GitHubResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js:134:53)
    at _fulfilled (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 6.2.1
OS: Linux 3.13.0-62-generic x64

Thanks

Yoel

**Comment by ghost** [comment]
Same for me

**Comment by jpduckwo** [comment]
Same problem for me too

**Comment by chozzz** [comment]
Any fix for this yet?

**Comment by tipodisimmia** [comment]
Same

**Comment by tujlaky** [comment]
Same

**Comment by sagrawal31** [comment]
I too have the same problem. Just fork the repo and remove the `version` from `bower.json`
